name: backendCICD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR-
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" >> aws_access_key_id
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY}}" >> aws_secret_access_key
          aws configure set aws_access_key_id "$(cat aws_access_key_id)"
          aws configure set aws_secret_access_key "$(cat aws_secret_access_key)"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 332931378908.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: |
          cd backend
          docker build -t backend .

      - name: Tag Docker image
        run: docker tag backend:latest 332931378908.dkr.ecr.us-east-1.amazonaws.com/kajal-mishra-niraj:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 332931378908.dkr.ecr.us-east-1.amazonaws.com/kajal-mishra-niraj:latest

      - name: SSH into EC2 instance and update Docker image
        uses: appleboy/ssh-action@master
        with:
          host: 18.212.186.118
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.AWS_ACCESS_KEY_ID_ECR }}" >> aws_access_key_id_ecr
            echo "${{ secrets.AWS_SECRET_ACCESS_KEY_ECR }}" >> aws_secret_access_key_ecr
            aws configure set aws_access_key_id "$(cat aws_access_key_id_ecr)"
            aws configure set aws_secret_access_key "$(cat aws_secret_access_key_ecr)"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 332931378908.dkr.ecr.us-east-1.amazonaws.com
            sudo docker stop backend-container || true
            sudo docker rm backend-container || true
            sudo docker pull 332931378908.dkr.ecr.us-east-1.amazonaws.com/kajal-mishra-niraj:latest
            sudo docker run -d --name backend-container -p 5000:5000 332931378908.dkr.ecr.us-east-1.amazonaws.com/kajal-mishra-niraj:latest
