name: Backend CI/CD

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd backend
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -umiskajal06541 --password-stdin
          sudo docker build -t miskajal06541/backend:latest .
          sudo docker images

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 3.84.61.52    
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker stop backend-container || true
            sudo docker rm backend-container || true
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u miskajal06541 --password-stdin
            sudo docker pull miskajal06541/backend:latest
            sudo docker run -d --name backend-container -p 5000:5000 miskajal06541/backend:latest
