name: Backend CI/CD

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t backend .
      
    - name: Save Docker image as tar
      run: docker save -o backend_image.tar backend:latest
      
    - name: Copy Docker image to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: ./backend_image.tar
        target: /home/ubuntu/backend_image.tar
      
    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker load -i /home/ubuntu/backend_image.tar
          docker stop backend-container || true
          docker rm backend-container || true
          docker run -d --name backend-container -p 5000:5000 backend:latest
