name: frontend Build and Deploy

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
      
    - name: Build production artifacts
      run: |
       cd frontend
       npm install
       npm run build
       ls
       cd ..
      
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.Iam_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.Iam_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        
    - name: Deploy to S3
      run: |
        aws s3 sync frontend/build/ s3://imaginekajal2
        # aws s3 sync frontend/build/ s3://imaginekajal2/ --acl bucket-owner-full-control

    - name: Set ACL to public-read
      run: |
        aws s3 cp --recursive --acl public-read ${GITHUB_WORKSPACE}/frontend/build/ s3://imaginekajal2/
